/*
  Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

  By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

  (Complete)
 */
#include <iostream>

unsigned int even_fibonacci_sum(unsigned int limit)
{
  unsigned int first = 1;
  unsigned int second = 1;
  unsigned int sum = 0;
  while (second <= limit) {
    unsigned int tmp = first + second;
    first = second;
    second = tmp;
    if (tmp % 2 == 0) sum += tmp;
  }
  return sum;
}

int main()
{
  std::cout << even_fibonacci_sum(4000000) << std::endl;
}
